### ISSUE TITLE
Only rxId is received 0

### ISSUE THREAD

**Issue by jainil3010** [Metaln00b/NodeMCU-BlackBox#3]
when I receive rxId then it will give me a 0. I am not using LCD screen I am printing on Serial moniter.

**Comment by Metaln00b** [comment]
Please post your source code. Maybe the Serial.print has a problem with rxId.

Note:

    Serial.print(x);       // print as an ASCII-encoded decimal - same as "DEC"

    Serial.print(x, DEC);  // print as an ASCII-encoded decimal

    Serial.print(x, HEX);  // print as an ASCII-encoded hexadecimal

    Serial.print(x, OCT);  // print as an ASCII-encoded octal

    Serial.println(x, BIN);  // print as an ASCII-encoded binary
